---
title: "Homework 2.1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## Diamonds dataset

```{r, warning=FALSE,message=FALSE}
library(knitr)
library(gridExtra)
library(ggplot2)
```

```{r, results='asis', echo=TRUE}
diamonds <- read.table("HW-diamonds.txt", header=FALSE, col.names = c('caratage', 'color_purity', 'clarity', 'cert', 'price'))
kable(diamonds[1:5,])
```

## Caratage

```{r}
G1 <- ggplot(diamonds, aes(x=caratage, y=price)) + geom_point() + geom_smooth(method = "lm")
G2 <- ggplot(diamonds, aes(x=caratage, y=log(price))) + geom_point() + geom_smooth(method = "lm")
grid.arrange(G1,G2,ncol=2)
```

## Categorical information

```{r}
# reorder
diamonds$color_purity = relevel(diamonds$color_purity, ref="I")
diamonds$clarity      = relevel(diamonds$clarity, ref="VS2")
diamonds$cert         = relevel(diamonds$cert, ref="HRD")

# fit model
lm1 = lm(formula = log(price) ~ caratage + color_purity + clarity + cert, data=diamonds)
summary(lm1)

#Comment on the model ô°tted, and perform a basic analysis of the residuals (normality, constant variance, independence, you may also want to use the function outlierTest or residualPlot).
```