---
title: "Homework 4"
output:
  html_document:
    df_print: paged
---

```{r, include=FALSE}
library("gridExtra")
library("ggplot2")
library("knitr")
library("kableExtra")
library("ggpubr")
```

```{r, include=FALSE}
## Differences after five years
clinical.stage = data.frame( 
  "cat" = c("I","II1","II2","III","IV"),
  "10-19" = c(0.25,0.3,0.25,0,0.2),
  "20-29" = c(0.25,0.3,0.25,0,0.2),
  "30-39" = c(0.5, 0.25, 0.15, 0, 0.1),
  "40-44" = c(0.6, 0.2, 0.1, 0, 0.1),
  "45-49" = c(0.6, 0.2, 0.1, 0, 0.1),
  "50-54" = c(0.6, 0.2, 0.1, 0, 0.1),
  "55-59" = c(0.6, 0.2, 0.1, 0, 0.1),
  "60-64" = c(0.5, 0.25, 0.15, 0, 0.1),
  "65-69" = c(0.425,0.275,0.15,0.01,0.14),
  "70-79" = c(0.25,0.35,0.25,0.1,0.14),
  "80-89" = c(0.25,0.35,0.25,0.1,0.14),
  "90+" = c(0.2,0.28,0.22,0.1,0.2)
)

clinical.stage.compact = data.frame( 
  "cat" = c("I","II1","II2","III","IV"),
  "from10to29" = c(0.25,0.3,0.25,0,0.2),
  "from30to39" = c(0.5, 0.25, 0.15, 0, 0.1),
  "from40to59" = c(0.6, 0.2, 0.1, 0, 0.1),
  "from60to64" = c(0.5, 0.25, 0.15, 0, 0.1),
  "from65to69" = c(0.425,0.275,0.15,0.01,0.14),
  "from70to89" = c(0.25,0.35,0.25,0.1,0.14),
  "from90to99" = c(0.2,0.28,0.22,0.1,0.2)
)
```

```{r eval=FALSE, include=FALSE}
histological.classification = data.frame( 
  "cat" = c("LOW_GRADE", "HIGH_GRADE"),
  "10-19" =
  "20-29" =
  "30-39" =
  "40-44" =
  "45-49" =
  "50-54" =
  "55-59" =
  "60-64" =
  "65-69" =
  "70-79" =
  "80-89" =
  "90+" =
)
```

```{r, include=FALSE}
var.overview.clinical <- function(df) {
  #t = tableGrob(df)
  p1 = ggplot(df, aes(x="", y=from10to29, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("10 - 29")+ geom_text(aes(label=from10to29), position = position_stack(vjust = 0.5))
  p2 = ggplot(df, aes(x="", y=from30to39, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("30 - 39")+ geom_text(aes(label=from30to39), position = position_stack(vjust = 0.5))
  p3 = ggplot(df, aes(x="", y=from40to59, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("40 - 59")+ geom_text(aes(label=from40to59), position = position_stack(vjust = 0.5))
  p4 = ggplot(df, aes(x="", y=from60to64, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("60 - 64")+ geom_text(aes(label=from60to64), position = position_stack(vjust = 0.5))
  p5 = ggplot(df, aes(x="", y=from65to69, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("65 - 69")+ geom_text(aes(label=from65to69), position = position_stack(vjust = 0.5))
  p6 = ggplot(df, aes(x="", y=from70to89, fill=cat)) + geom_bar(stat="identity", width=1) + guides(fill=FALSE) + ylab("70 - 89")+ geom_text(aes(label=from70to89), position = position_stack(vjust = 0.5))
  p7 = ggplot(df, aes(x="", y=from90to99, fill=cat)) + geom_bar(stat="identity", width=1) + ylab(" 90 + ")+ geom_text(aes(label=from90to99), position = position_stack(vjust = 0.5))
  return(ggarrange(p1, p2, p3, p4, p5, p6, p7, ncol = 4,nrow = 2, common.legend = TRUE, legend = c("right")))
}
```

### Clinical stage


```{r, echo=FALSE, fig.height = 8, fig.width = 10}
var.overview.clinical(clinical.stage.compact)
```
